blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/vibing-ai/sport-scribe/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/vibing-ai/sport-scribe/tree/main/docs
    about: Check our documentation for guides and API references
  - name: 🐛 Security Issues
    url: https://github.com/vibing-ai/sport-scribe/security/advisories
    about: Report security vulnerabilities privately
